"""Tests for the parsing wizard."""
from __future__ import annotations

import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from ff3_importer.io_loader import load_csv
from ff3_importer.parse_wizard import parse_with_wizard


class ParseWizardTests(unittest.TestCase):
    """Test cases for the parsing wizard."""
    def test_parse_skips_metadata_and_maps_headers(self) -> None:
        """Test that parse skips metadata and maps headers."""
        content = "\n".join(
            [
                "Report generated by My Bank",
                "Account: 1234",
                "Date,Description,Amount",
                "2026-02-01,Coffee,-4.50",
                "2026-02-02,Salary,1200.00",
            ]
        )
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "statement.csv"
            path.write_text(content, encoding="utf-8")
            loaded = load_csv(path)
            with patch("ff3_importer.parse_wizard._is_interactive", return_value=False):
                parsed = parse_with_wizard(loaded)
            self.assertEqual(parsed.headers, ["Date", "Description", "Amount"])
            self.assertEqual(len(parsed.rows), 2)
            self.assertEqual(parsed.rows[0]["Description"], "Coffee")
            self.assertEqual(parsed.parse_hints["header_row_index"], 2)


if __name__ == "__main__":
    unittest.main()
